version: '3.5'

services:
  red-cache:
    container_name: red-cache
    image: redis
    #command: redis-server --requirepass SUASENHA --appendonly yes
    command: redis-server --appendonly yes
    hostname: red-cache
    ports:
      - "6379:6379"
    volumes:
      - /home/xawe/Redis:/var/lib/postgresql/data
    networks:
      - micro-net

  red-rabbit:
    container_name: red-rabbit
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:$HOME/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:$HOME/var/log/rabbitmq
    networks:
        - micro-net
  red-data-in:
    container_name: red-data-in
    image: postgres    
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - micro-net
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - micro-net
    restart: unless-stopped
networks:   
  micro-net:
    name: micro-space-network
    driver: bridge
volumes:
    postgres:
    pgadmin: